### Consider the below code to answer further questions:

In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)


### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
#### Ans:

A list is a built-in Python data type that can hold elements of any data type.

An array is a data structure provided by the NumPy library that is designed to hold elements of the same data type.

In [2]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

#### Ans:

In [3]:
print('Data Type of list_ elements:')
for elem in list_:
    print(type(elem))
print('Data Type of array_list elements:')
for elem in array_list:
    print(type(elem))

Data Type of list_ elements:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data Type of array_list elements:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

**array_list = np.array(object = list_, dtype = int)**

### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

#### Ans:

In [4]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data type of the elements present in list_ and array_list 

The dtype parameter is set to int, which means that all the elements in the new NumPy array will be cast to integers.

In [5]:
print('Data Type of list_ elements:')
for elem in list_:
    print(type(elem))
print('Data Type of array_list elements:')
for elem in array_list:
    print(type(elem))

Data Type of list_ elements:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data Type of array_list elements:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Consider the below code to answer further questions:

In [6]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:

**(i) shape**

**(ii) size**


#### Ans:

In [7]:
print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]


#### Ans:

In [8]:
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
#### Ans:

In [9]:
eye_array = np.eye((5))

print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
